extends Node

var in_dialogue = false
var finished_dialogue = false
var finished_sec_dialogue = false
var finished_aq = false
var finished_final = false
var rang = false
var gameover = false
var house = false
var played = false
var finished_compdial = false
var paused = false
var item = "No Items Available"
var opened_crate = false
var finished_rec_dialogue = false
var killRec = false
var lost = false
var elevator_route = false
var recKilled = false
var killBro = false
var saveBro = false
var finished_bro_dialogue = false
var broKilled = false
var broSaved = false
var finished_kill_dial = false
var finished_save_dial = false
var finished_sec_visit_dial = false
var finished_boss_dial = false
var objective = ""
